# action.yml
name: 'Configure Tramline'
description: 'Checkout the correct ref & parse JSON inputs'
branding:
  icon: 'arrow-down-circle'
  color: 'green'
inputs:
  input:
    description: "Input from Tramline as a JSON blob"
    required: true
    default: "{}"
outputs:
  version_code:
    description: 'the version code (build number) for the build'
    value: ${{ steps.tramline.outputs.version_code }}
  version_name:
    description: 'the version name for the build'
    value: ${{ steps.tramline.outputs.version_name }}
  commit_ref:
    description: 'the commit for which this workflow is triggered'
    value: ${{ steps.tramline.outputs.commit_ref }}
  build_notes:
    description: 'the testing notes for the build'
    value: ${{ steps.tramline.outputs.build_notes }}
runs:
  using: "composite"
  steps:
    - name: setup-jq
      uses: dcarbone/install-jq-action@v2.1.0
      with:
          version: '1.7'
          # Setting this to true will install the version you specify into the tool cache
          # superseding the preinstalled version
          force: true

    - name: Parse inputs from Tramline
      run: |
        # Read JSON
        echo '${{ inputs.input }}' > tramline_input.json

        # Parse JSON and store keys
        keys=$(jq -r 'keys_unsorted[]' tramline_input.json)

        # Exit if there are parse errors
        if [ -z "$keys" ]; then
            echo "Error parsing Tramline inputs. Exiting..."
            exit 1
        fi

        # Iterate through the keys and set variables
        for key in $keys; do
            # Set output in a temp file to avoid large variables
            tmp_file=$(mktemp)

            jq -r --arg k "$key" '.[$k]' tramline_input.json | \
            awk '{
                # Replace literal newlines with %0A
                gsub(/\n/,"%0A");
                # Print the processed line
                print
            }' > "$tmp_file"

            echo "${key}=$(cat "$tmp_file")"

            # Remove temp file
            rm -f "$tmp_file"
        done

        # Cleanup
        rm -f tramline_input.json
        echo "Finishing up tramline input parsing..."
        EOL

        chmod +x parse_input.sh
        ./parse_input.sh
      id: tramline
      shell: bash

    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.tramline.outputs.commit_ref }}
